#!/bin/sh

XPRA_DEFAULT_PORT=2345
XPRA_DEFAULT_DISPLAY=:42

get_first_xpra_display()
{
  xpra list | sed -n 's/^.* session at \(.*\)/\1/p' | head -n 1
}

if [ -z "$DISPLAY" ]; then
  XPRADISPLAY=$(get_first_xpra_display)
  if [ -z "$XPRADISPLAY" ]; then
    xpra start --bind-tcp=0.0.0.0:${XPRA_DEFAULT_PORT} ${XPRA_DEFAULT_DISPLAY} 1>&2
    XPRADISPLAY=${XPRA_DEFAULT_DISPLAY}
  fi
  export DISPLAY=${XPRADISPLAY}
fi